services:
  nitter:
    image: ghcr.io/sekai-soft/nitter-self-contained
    container_name: nitter
    volumes:
      - nitter:/nitter-data
    environment:
      TWITTER_USERNAME: ${BURNER_TWITTER_USERNAME}
      TWITTER_PASSWORD: ${BURNER_TWITTER_PASSWORD}
      NITTER_ACCOUNTS_FILE: /nitter-data/guest_accounts.json
      DISABLE_NGINX: "1"
      INSTANCE_HOSTNAME: nitter
      INSTANCE_PORT: "80"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:80 || exit 1
      interval: 5s
      timeout: 5s
      retries: 12
  minalinsky:
    build: .
    volumes:
      - ./dbs:/app/dbs
    environment:
      SQLITE_FILE: /app/dbs/db.db
      NITTER_HOST: nitter
      NITTER_HTTPS: 'false'
      TWITTER_HANDLE: ${TWITTER_HANDLE}
      MASTODON_HOST: ${MASTODON_HOST}
      MASTODON_CLIENT_ID: ${MASTODON_CLIENT_ID}
      MASTODON_CLIENT_SECRET: ${MASTODON_CLIENT_SECRET}
      MASTODON_ACCESS_TOKEN: ${MASTODON_ACCESS_TOKEN}
      MASTODON_STATUS_LIMIT: '10'  # set the maximum of statuses to be posted at once
      INTERVAL_MINUTES: '1'
volumes:
  nitter:
